import React from 'react';

export default function IndexSectionCustomComponents9() {
    return (
        <React.Fragment>
            <>
                <section className="py-12 bg-gray-50 bs-section-dragged md:hidden">  <div className="mx-auto px-4">    <div className="mx-auto max-w-3xl">      <h2 className="mb-8 text-2xl md:text-4xl leading-tight text-darkCoolGray-900 font-bold tracking-tighter">特別商品セクション</h2>      <p className="mb-12 text-lg md:text-xl text-coolGray-500 font-medium">今月の限定商品をご紹介します。期間限定の特別価格でお求めいただけます。</p>      <div className="flex flex-col md:flex-row justify-between">        {/* &#21830;&#21697;1 */}        <div className="w-full md:w-1/2 px-4 mb-8">          <div className="bg-white rounded-lg shadow-md overflow-hidden">            <div className="relative">              <img className="w-full h-64 object-cover" src="https://placehold.co/600x400" alt="商品1" />          </div>            <div className="p-6">              <h3 className="mb-2 text-xl md:text-2xl leading-tight text-darkCoolGray-900 font-bold tracking-tighter">プレミアムセラミックマグ</h3>              <p className="mb-4 text-coolGray-500">耐熱性と保温性に優れた、デザイン性の高いセラミックマグ。日常使いにぴったりです。</p>              <div className="mb-4 flex items-center">                <span className="text-2xl font-bold text-green-600">¥3,800</span>                <span className="ml-2 text-sm line-through text-coolGray-400">¥4,500</span>            </div>              <button className="inline-block py-3 px-7 w-full text-lg leading-7 text-white bg-black hover:bg-gray-800 font-medium text-center focus:ring-2 focus:ring-black focus:ring-opacity-50 border border-transparent rounded-md shadow-sm transition duration-200">カートに追加</button>          </div>        </div>      </div>        {/* &#21830;&#21697;2 */}        <div className="w-full md:w-1/2 px-4 mb-8">          <div className="bg-white rounded-lg shadow-md overflow-hidden">            <div className="relative">              <img className="w-full h-64 object-cover" src="https://placehold.co/600x400" alt="商品2" />          </div>            <div className="p-6">              <h3 className="mb-2 text-xl md:text-2xl leading-tight text-darkCoolGray-900 font-bold tracking-tighter">オーガニックコットン</h3>              <p className="mb-4 text-coolGray-500">100%オーガニックコットン素材を使用した、肌触りのよい高品質ブランケットです。</p>              <div className="mb-4 flex items-center">                <span className="text-2xl font-bold text-green-600">¥6,500</span>                <span className="ml-2 text-sm line-through text-coolGray-400">¥8,000</span>            </div>              <button className="inline-block py-3 px-7 w-full text-lg leading-7 text-white bg-black hover:bg-gray-800 font-medium text-center focus:ring-2 focus:ring-black focus:ring-opacity-50 border border-transparent rounded-md shadow-sm transition duration-200">カートに追加</button>          </div>        </div>      </div>    </div>  </div></div></section>


            </>
        </React.Fragment>
    );
}

